-- Run this in your Supabase SQL Editor to create the required tables

-- Users table
create table if not exists users (
    id uuid primary key default gen_random_uuid(),
    email text unique not null,
    password_hash text not null,
    created_at timestamptz default now()
);

-- Deribit API keys (encrypted)
create table if not exists deribit_keys (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references users(id) on delete cascade unique,
    client_id_enc text not null,
    client_secret_enc text not null,
    created_at timestamptz default now(),
    updated_at timestamptz default now()
);

-- Trade signals generated by the agent
create table if not exists trade_signals (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references users(id) on delete cascade,
    asset text not null,
    direction text not null,          -- 'call' or 'put'
    bias_pct float not null,          -- e.g. 78.5 means 78.5% of paths favor this direction
    crps_score float,                 -- confidence score from Synth
    pop float,                        -- probability of profit
    strike_price float,
    entry_price float,
    status text default 'pending',    -- 'pending', 'executed', 'expired', 'cancelled'
    created_at timestamptz default now()
);

-- Trade history
create table if not exists trades (
    id uuid primary key default gen_random_uuid(),
    user_id uuid references users(id) on delete cascade,
    signal_id uuid references trade_signals(id),
    asset text not null,
    direction text not null,
    strike_price float not null,
    entry_price float not null,
    exit_price float,
    budget float not null,
    pnl float,
    status text default 'open',       -- 'open', 'closed', 'stopped'
    deribit_order_id text,
    opened_at timestamptz default now(),
    closed_at timestamptz
);
